### ISSUE TITLE
supported file formats

### ISSUE THREAD

**Issue by sunt05** [oovm/wolfram-exchange#1]
This project looks great! 
Just curious to know: what are the supported formats?

**Comment by oovm** [comment]
Now supports json, yaml, toml and pickle,

https://github.com/GalAster/wolfram-exchange/blob/5c2dcba85bd6c7e77d42c2d0c876bd8b13571934/projects/wolfram-lib/Cargo.toml#L20-L25

If you want to support other formats, you must first have a rust-implemented parser or cbind parser.

**Comment by sunt05** [comment]
thanks for the reply; clear now 👍
